### ISSUE TITLE
score value + parseInt

### ISSUE THREAD

**Issue by derekfogge** [cynthiakellogg/quiz-app#1]
Hey Cynthia, 

I had a chance to look this over again, and doing the following got rid of that `NaN` bug for me.

Delete the `score` variable in the submit function's else statement:
```
var score = parseInt($('input[type="radio"]:checked', '#formAnswer').val());
```

Put this `score` variable at the very top of the submit function instead:
```
var score = $('input[type="radio"]:checked');
```

  

Then, replace:
```
addPoints = addPoints + score;
console.log(score);
```

...with:
```
addPoints = addPoints + parseInt(score.val());
console.log(score.val());
```

Let me know if that does the trick!

**Comment by cynthiakellogg** [comment]
this is a great feature(issues notes)! thanks!
